package com.javaprac.webforum;

import org.testng.annotations.*;
import static org.testng.Assert.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import java.time.Duration;

public class CheckSectionAccess {
  private WebDriver driver;
  private StringBuffer verificationErrors = new StringBuffer();

  @BeforeClass(alwaysRun = true)
  public void setUp() throws Exception {
    System.setProperty("webdriver.chrome.driver", "");
    driver = new FirefoxDriver();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(1));
  }

  @Test
  public void testCheckSectionAccess() throws Exception {
    driver.get("http://localhost:8080/");
    driver.findElement(By.id("bar_auth_button")).click();
    driver.findElement(By.id("input_email")).clear();
    driver.findElement(By.id("input_email")).sendKeys("boss@webforum.net");
    driver.findElement(By.id("input_password")).clear();
    driver.findElement(By.id("input_password")).sendKeys("qwerty");
    driver.findElement(By.id("auth_button")).click();
    driver.findElement(By.cssSelector("h5")).click();
    driver.findElement(By.id("collapseButton")).click();
    driver.findElement(By.id("new_user_nick")).click();
    driver.findElement(By.id("new_user_nick")).clear();
    driver.findElement(By.id("new_user_nick")).sendKeys("public_user");
    driver.findElement(By.id("new_user_login")).click();
    driver.findElement(By.id("new_user_login")).clear();
    driver.findElement(By.id("new_user_login")).sendKeys("pu@webforum.net");
    driver.findElement(By.id("new_user_password")).click();
    driver.findElement(By.id("new_user_password")).clear();
    driver.findElement(By.id("new_user_password")).sendKeys("");
    driver.findElement(By.id("new_user_create")).click();
    driver.findElement(By.id("collapseButton")).click();
    driver.findElement(By.id("new_user_nick")).click();
    driver.findElement(By.id("new_user_nick")).clear();
    driver.findElement(By.id("new_user_nick")).sendKeys("u_with_role");
    driver.findElement(By.id("new_user_login")).click();
    driver.findElement(By.id("new_user_login")).click();
    driver.findElement(By.id("new_user_login")).clear();
    driver.findElement(By.id("new_user_login")).sendKeys("role@webforum.net");
    driver.findElement(By.id("new_user_password")).click();
    driver.findElement(By.id("new_user_password")).clear();
    driver.findElement(By.id("new_user_password")).sendKeys("");
    driver.findElement(By.id("add_button")).click();
    driver.findElement(By.id("add_role_link")).click();
    driver.findElement(By.id("role_row_0")).click();
    driver.findElement(By.id("role_row_0")).clear();
    driver.findElement(By.id("role_row_0")).sendKeys("role");
    driver.findElement(By.id("new_user_create")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.linkText("+ создать раздел")).click();
    driver.findElement(By.id("section_name")).clear();
    driver.findElement(By.id("section_name")).sendKeys("Раздел без настроек доступа");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).clear();
    driver.findElement(By.id("description")).sendKeys("В данном разделе все пользователи, не являющиеся админами имеют право на чтение.");
    driver.findElement(By.id("perm_tbl_create_button")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.linkText("+ создать раздел")).click();
    driver.findElement(By.id("section_name")).click();
    driver.findElement(By.id("section_name")).clear();
    driver.findElement(By.id("section_name")).sendKeys("Закрытый раздел");
    driver.findElement(By.id("description")).clear();
    driver.findElement(By.id("description")).sendKeys("В данном разделе право на запись имеют пользователи только определенной роли.");
    driver.findElement(By.id("perm_tbl_add_button")).click();
    driver.findElement(By.id("perm_tbl_role_0")).click();
    driver.findElement(By.id("perm_tbl_role_0")).clear();
    driver.findElement(By.id("perm_tbl_role_0")).sendKeys("role");
    driver.findElement(By.id("perm_tbl_perm_0")).clear();
    driver.findElement(By.id("perm_tbl_perm_0")).sendKeys("WRITE");
    driver.findElement(By.id("perm_tbl_create_button")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.linkText("+ создать раздел")).click();
    driver.findElement(By.id("section_name")).click();
    driver.findElement(By.id("section_name")).clear();
    driver.findElement(By.id("section_name")).sendKeys("Раздел с расширенными правами для определенной группы");
    driver.findElement(By.id("description")).clear();
    driver.findElement(By.id("description")).sendKeys("В данном разделе осуществяется публичный доступ на чтение и доступ на запись только для пользователей с заданной ролью");
    driver.findElement(By.id("perm_tbl_add_button")).click();
    driver.findElement(By.id("perm_tbl_role_0")).click();
    driver.findElement(By.id("perm_tbl_role_0")).clear();
    driver.findElement(By.id("perm_tbl_role_0")).sendKeys("role");
    driver.findElement(By.id("perm_tbl_perm_0")).clear();
    driver.findElement(By.id("perm_tbl_perm_0")).sendKeys("WRITE");
    driver.findElement(By.id("perm_tbl_add_button")).click();
    driver.findElement(By.id("perm_tbl_role_1")).click();
    driver.findElement(By.id("perm_tbl_role_1")).clear();
    driver.findElement(By.id("perm_tbl_role_1")).sendKeys("public");
    driver.findElement(By.id("perm_tbl_perm_1")).clear();
    driver.findElement(By.id("perm_tbl_perm_1")).sendKeys("READ");
    driver.findElement(By.id("perm_tbl_create_button")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.linkText("+ создать раздел")).click();
    driver.findElement(By.id("section_name")).click();
    driver.findElement(By.id("section_name")).clear();
    driver.findElement(By.id("section_name")).sendKeys("Раздел с публичным доступом на запись");
    driver.findElement(By.id("description")).clear();
    driver.findElement(By.id("description")).sendKeys("В данном разделе осуществяется доступ на запись для всех авторизованных пользователей и доступ на чтение для неавторизованных");
    driver.findElement(By.id("perm_tbl_add_button")).click();
    driver.findElement(By.id("perm_tbl_role_0")).click();
    driver.findElement(By.id("perm_tbl_role_0")).clear();
    driver.findElement(By.id("perm_tbl_role_0")).sendKeys("public");
    driver.findElement(By.id("perm_tbl_perm_0")).clear();
    driver.findElement(By.id("perm_tbl_perm_0")).sendKeys("WRITE");
    driver.findElement(By.id("perm_tbl_create_button")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел без настроек доступа')]")).click();
    driver.findElement(By.id("create_discussion_button")).click();
    driver.findElement(By.id("section_name")).click();
    driver.findElement(By.id("section_name")).clear();
    driver.findElement(By.id("section_name")).sendKeys("test");
    driver.findElement(By.id("create_button")).click();
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Закрытый раздел')]")).click();
    driver.findElement(By.id("create_discussion_button")).click();
    driver.findElement(By.id("section_name")).click();
    driver.findElement(By.id("section_name")).clear();
    driver.findElement(By.id("section_name")).sendKeys("test");
    driver.findElement(By.id("create_button")).click();
    driver.findElement(By.id("bar_main_title")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел с расширенными правами для определенной группы')]")).click();
    driver.findElement(By.id("create_discussion_button")).click();
    driver.findElement(By.id("section_name")).click();
    driver.findElement(By.id("section_name")).clear();
    driver.findElement(By.id("section_name")).sendKeys("test");
    driver.findElement(By.id("create_button")).click();
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел с публичным доступом на запись')]")).click();
    driver.findElement(By.id("create_discussion_button")).click();
    driver.findElement(By.id("section_name")).click();
    driver.findElement(By.id("section_name")).clear();
    driver.findElement(By.id("section_name")).sendKeys("test");
    driver.findElement(By.id("create_button")).click();
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.id("bar_auth_button")).click();
    driver.findElement(By.linkText("Выйти")).click();
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел без настроек доступа')]")).click();
    assertEquals(driver.getTitle(), "Раздел без настроек доступа");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertFalse(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Закрытый раздел')]")).click();
    assertEquals(driver.getTitle(), "Нет доступа");
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел с расширенными правами для определенной группы')]")).click();
    assertEquals(driver.getTitle(), "Раздел с расширенными правами для определенной группы");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertFalse(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел с публичным доступом на запись')]")).click();
    assertEquals(driver.getTitle(), "Раздел с публичным доступом на запись");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertFalse(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.id("bar_main_title")).click();
    driver.findElement(By.id("bar_auth_button")).click();
    driver.findElement(By.id("input_email")).click();
    driver.findElement(By.id("input_email")).clear();
    driver.findElement(By.id("input_email")).sendKeys("pu@webforum.net");
    driver.findElement(By.id("input_password")).clear();
    driver.findElement(By.id("input_password")).sendKeys("");
    driver.findElement(By.id("auth_button")).click();
    assertEquals(driver.findElement(By.id("bar_auth_button")).getText(), "public_user");
    driver.findElement(By.xpath("//a[contains(text(),'Раздел без настроек доступа')]")).click();
    assertEquals(driver.getTitle(), "Раздел без настроек доступа");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertFalse(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Закрытый раздел')]")).click();
    assertEquals(driver.getTitle(), "Нет доступа");
    driver.findElement(By.cssSelector("h3")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел с расширенными правами для определенной группы')]")).click();
    assertEquals(driver.getTitle(), "Раздел с расширенными правами для определенной группы");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertFalse(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел с публичным доступом на запись')]")).click();
    assertEquals(driver.getTitle(), "Раздел с публичным доступом на запись");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertTrue(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.id("bar_auth_button")).click();
    driver.findElement(By.linkText("Выйти")).click();
    driver.findElement(By.id("input_email")).click();
    driver.findElement(By.id("input_email")).clear();
    driver.findElement(By.id("input_email")).sendKeys("role@webforum.net");
    driver.findElement(By.id("input_password")).clear();
    driver.findElement(By.id("input_password")).sendKeys("");
    driver.findElement(By.id("auth_button")).click();
    assertEquals(driver.findElement(By.id("bar_auth_button")).getText(), "u_with_role");
    driver.findElement(By.xpath("//a[contains(text(),'Раздел без настроек доступа')]")).click();
    assertEquals(driver.getTitle(), "Раздел без настроек доступа");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertFalse(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Закрытый раздел')]")).click();
    assertEquals(driver.getTitle(), "Закрытый раздел");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertTrue(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел с расширенными правами для определенной группы')]")).click();
    assertEquals(driver.getTitle(), "Раздел с расширенными правами для определенной группы");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertTrue(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.xpath("//a[contains(text(),'Раздел с публичным доступом на запись')]")).click();
    assertEquals(driver.getTitle(), "Раздел с публичным доступом на запись");
    driver.findElement(By.id("discussion_0")).click();
    assertEquals(driver.getTitle(), "test");
    assertTrue(isElementPresent(By.id("new_msg_input")));
    driver.findElement(By.cssSelector("h3:nth-child(1)")).click();
    driver.findElement(By.id("bar_auth_button")).click();
    driver.findElement(By.linkText("Выйти")).click();
    driver.findElement(By.id("input_email")).clear();
    driver.findElement(By.id("input_email")).sendKeys("boss@webforum.net");
    driver.findElement(By.id("input_password")).clear();
    driver.findElement(By.id("input_password")).sendKeys("qwerty");
    driver.findElement(By.id("auth_button")).click();
    driver.findElement(By.id("section_0_link")).click();
    driver.findElement(By.id("delete_discussion_button")).click();
    driver.findElement(By.id("section_0_link")).click();
    driver.findElement(By.id("delete_discussion_button")).click();
    driver.findElement(By.id("section_1_link")).click();
    driver.findElement(By.id("delete_discussion_button")).click();
    driver.findElement(By.id("section_0_link")).click();
    driver.findElement(By.id("delete_discussion_button")).click();
    driver.findElement(By.cssSelector("h5")).click();
    driver.findElement(By.id("user_link_1")).click();
    driver.findElement(By.linkText("- удалить пользователя")).click();
    driver.findElement(By.cssSelector("h5")).click();
    driver.findElement(By.id("user_link_1")).click();
    driver.findElement(By.linkText("- удалить пользователя"));
  }

  @AfterClass(alwaysRun = true)
  public void tearDown() throws Exception {
    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }
}
